version: "3.9"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - network-backend

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - network-backend

  web:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb:
