version: "3.9"
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongo:/data/db
    networks:
      - network-backend

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - network-backend

  web:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - network-backend

volumes:
  mongo:

networks:
  network-backend:
